# Generated by Django 4.2.2 on 2023-07-06 09:46
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='StudentDeatils',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]


